#!/bin/bash

# System Information
USER=$(whoami)
DATE=$(date)
#Get hostname of the system
HOSTNAME=$(hostname)
#Get the OS name and version
OS=$(awk -F= 'NR<=3 && /^NAME|^VERSION/{gsub(/\"/, "", $2); printf "%s %s", $2, $3}' /etc/os-release)
#Get the system uptime
UPTIME=$(uptime -p)

# Hardware Information
#Get CPU information from lshw output
CPU=$(lshw -class processor | grep -m 1 'product' | cut -d ':' -f 2 | sed 's/^[ \t]*//')
cpu_SPEED=$(lshw -class processor | grep -m 1 'capacity' | cut -d ':' -f 2 | sed 's/^[ \t]*//')

#Get RAM info using free command
Ram=$(free -h | awk '/^Mem/{print $2}')
#Get disk info using lsblk command
DISKS=$(lsblk -d -o NAME,SIZE,MODEL | grep -v "NAME")
VIDEO=$(lspci | grep -i vga | awk -F '[:()]' '{print $3}')

# Network Information
FQDN=$(hostname -f)
#Get ip address of the system
HOST_IPADDRESS=$(hostname -I)
#Get the default gateway IP address
GATEWAY=$(ip route | awk '/default via/{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | awk '/nameserver/{print $2}')

#Get network interface names and  their corresponding IP addresses
INTERFACE=$(ip -o -4 addr show | awk '!/^[0-9]*: ?lo|link\/ether/ {print $2}' | paste -sd "," -)
IP_ADDRESS=$(ip -o -4 addr show | awk '!/^[0-9]*: ?lo|link\/ether/ {print $4}' | cut -d'/' -f1 | paste -sd "," -)

# System Status
USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',')
DISK_SPACE=$(df -h | awk '!/Filesystem/{print $4,$6}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1",",$2",",$3}')
MEMORY_ALLOC=$(free -h | awk '/Mem/{print "Total:",$2,"Used:",$3,"Free:",$4}')
LISTENING_PORTS=$(ss -tuln | awk 'NR>1{print $4}' | awk -F: '{print $NF}' | sort -n | uniq | tr '\n' ',')
#Get UFW rules
UFW_RULES=$(sudo ufw status numbered)

cat <<EOF

System Report generated by $USER, $DATE

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
cpu: $CPU
Speed: $cpu_SPEED
RAM: $Ram
Disk(s): 
$DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_IPADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER

Interface: $INTERFACE
IP Address: $IP_ADDRESS

System Status
-------------
Users Logged In: $USERS
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOC
Listening Network Ports: $LISTENING_PORTS
UFW Rules: $UFW_RULES

EOF
