#!/bin/bash

# System Information
HOSTNAME=$(hostname)
OS=$(sw_vers -productName)
UPTIME=$(uptime -p)

# Hardware Information
CPU=$(sysctl -n machdep.cpu.brand_string)
RAM=$(sysctl -n hw.memsize | awk '{print $0/1024^3 " GB"}')
DISKS=$(diskutil list | grep "0:" | awk '{print $3, $4}')
VIDEO=$(system_profiler SPDisplaysDataType | grep Chipset | awk -F': ' '{print $2}')

# Network Information
FQDN=$(hostname -f)
HOST_ADDRESS=$(ipconfig getifaddr en0) 
GATEWAY=$(netstat -nr | grep default | awk '{print $2}')
DNS_SERVER=$(scutil --dns | grep nameserver | awk '{print $3}')

INTERFACE=$(ifconfig -l)
IP_ADDRESS=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | paste -sd "," -)

# System Status
USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',')
DISK_SPACE=$(df -h | awk '!/Filesystem/{print $4,$6}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(sysctl -n vm.loadavg)
MEMORY_ALLOC=$(top -l 1 | awk '/PhysMem/ {print "Total:", $8, "Used:", $2, "Free:", $6}')
LISTENING_PORTS=$(netstat -an | grep LISTEN | awk '{print $4}' | awk -F ':' '{print $NF}' | sort -n | uniq | tr '\n' ',')
UFW_RULES=$(sudo ufw status numbered)

cat <<EOF


System Report generated by $USER, $(date)

System Information
_________________
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
___________________
CPU: $CPU
RAM: $RAM
DISKS:
$DISKS
Video: $VIDEO

Network Information
__________________
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER

Interface: $INTERFACE
IP Address: $IP_ADDRESS

System Status
_____________
Users Logged In: $USERS
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocations: $MEMORY_ALLOC
Listening Network Ports: $LISTENING_PORTS
UFW Rules: $UFW_RULES

EOF

